---

- name: Add EZProxy Group
  group:
    name: ezproxy
    state: present

- name: Add EZProxy user
  user:
    name: ezproxy
    group: ezproxy
    home: /srv/ezproxy/
    create_home: yes
    shell: /sbin/nologin
    system: yes
    state: present

- name: Copy new EZProxy 7.x binary
  copy: 
    src: ezproxy-linux.bin-7.1.14
    dest: /srv/ezproxy/ezproxy
    owner: ezproxy
    group: ezproxy
    mode: '0750'

- name: Re-validate WSkey
  command: /srv/ezproxy/ezproxy -k 123456789101112
  become: yes

- name: Copy GeoIP update tarball
  copy:
    src: geoipupdate_4.8.0_linux_amd64.rpm
    dest: /usr/local/src/
    owner: root
    group: root
    mode: '0755'

# installs GeoIPupdate to /usr/bin/
- name: Install GeoIPupdate rpm
  yum:
    name: /usr/local/src/geoipupdate_4.8.0_linux_amd64.rpm
    state: present

- name: Copy GeoIP.conf.j2
  template:
    src: GeoIP.conf.j2
    dest: /etc/GeoIP.conf
    owner: root
    group: root
    mode: '0755'

- name: Add crontab entry for GeoIP update
  cron:
    name: GeoID update
    job: "MAILTO=libops@ou.edu 0 0 * * 0 /usr/local/bin/geoipupdate"
    user: root

- name: Install service definition
  copy:
    src: ezproxy.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0755'

- name: Start ezproxy
  service:
    name: ezproxy
    enabled: yes
    state: started

